<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Etudiant;

class EtudiantSeeder extends Seeder
{
    public function run(): void
    {
        $etudiants = [
            [
                'nom' => 'Alami',
                'prenom' => 'Mohammed',
                'apogee' => '12345678',
                'cin' => 'AB123456',
                'email' => 'mohammed.alami@ensa.ac.ma',
                'date_naissance' => '2003-05-15',
                'lieu_naissance' => 'Casablanca',
                'telephone' => '+212 6 11 22 33 01',
                'adresse' => '25 Rue des Écoles, Casablanca',
                'status' => 'actif',
            ],
            [
                'nom' => 'Bennani',
                'prenom' => 'Fatima',
                'apogee' => '87654321',
                'cin' => 'CD789012',
                'email' => 'fatima.bennani@ensa.ac.ma',
                'date_naissance' => '2004-03-22',
                'lieu_naissance' => 'Rabat',
                'telephone' => '+212 6 11 22 33 02',
                'adresse' => '12 Avenue Mohammed V, Rabat',
                'status' => 'actif',
            ],
            [
                'nom' => 'Idrissi',
                'prenom' => 'Youssef',
                'apogee' => '11223344',
                'cin' => 'EF345678',
                'email' => 'youssef.idrissi@ensa.ac.ma',
                'date_naissance' => '2003-11-08',
                'lieu_naissance' => 'Fès',
                'telephone' => '+212 6 11 22 33 03',
                'adresse' => '8 Quartier Zouagha, Fès',
                'status' => 'actif',
            ],
            [
                'nom' => 'Tazi',
                'prenom' => 'Amina',
                'apogee' => '55667788',
                'cin' => 'GH901234',
                'email' => 'amina.tazi@ensa.ac.ma',
                'date_naissance' => '2004-07-19',
                'lieu_naissance' => 'Marrakech',
                'telephone' => '+212 6 11 22 33 04',
                'adresse' => '34 Rue de la Liberté, Marrakech',
                'status' => 'actif',
            ],
            [
                'nom' => 'Fassi',
                'prenom' => 'Karim',
                'apogee' => '99887766',
                'cin' => 'IJ567890',
                'email' => 'karim.fassi@ensa.ac.ma',
                'date_naissance' => '2001-02-14',
                'lieu_naissance' => 'Fès',
                'telephone' => '+212 6 11 22 33 05',
                'adresse' => '56 Boulevard Hassan II, Fès',
                'status' => 'diplome',
            ],
            [
                'nom' => 'El Amrani',
                'prenom' => 'Sara',
                'apogee' => '23456789',
                'cin' => 'KL234567',
                'email' => 'sara.elamrani@ensa.ac.ma',
                'date_naissance' => '2003-09-30',
                'lieu_naissance' => 'Tanger',
                'telephone' => '+212 6 11 22 33 06',
                'adresse' => '17 Avenue Ibn Batouta, Tanger',
                'status' => 'actif',
            ],
            [
                'nom' => 'Mansouri',
                'prenom' => 'Omar',
                'apogee' => '34567890',
                'cin' => 'MN345678',
                'email' => 'omar.mansouri@ensa.ac.ma',
                'date_naissance' => '2004-01-25',
                'lieu_naissance' => 'Meknès',
                'telephone' => '+212 6 11 22 33 07',
                'adresse' => '42 Rue Rouamzine, Meknès',
                'status' => 'actif',
            ],
            [
                'nom' => 'Cherkaoui',
                'prenom' => 'Leila',
                'apogee' => '45678901',
                'cin' => 'OP456789',
                'email' => 'zelallouche@gmail.com',
                'date_naissance' => '2003-06-12',
                'lieu_naissance' => 'Agadir',
                'telephone' => '+212 6 11 22 33 08',
                'adresse' => '23 Boulevard du 20 Août, Agadir',
                'status' => 'actif',
            ],
            [
                'nom' => 'Jabrane',
                'prenom' => 'Ahmed',
                'apogee' => '56789012',
                'cin' => 'QR567890',
                'email' => 'ahmed.jabrane@ensa.ac.ma',
                'date_naissance' => '2004-04-18',
                'lieu_naissance' => 'Oujda',
                'telephone' => '+212 6 11 22 33 09',
                'adresse' => '15 Avenue Allal Ben Abdellah, Oujda',
                'status' => 'actif',
            ],
            [
                'nom' => 'Kabbouri',
                'prenom' => 'Nadia',
                'apogee' => '67890123',
                'cin' => 'ST678901',
                'email' => 'nadia.kabbouri@ensa.ac.ma',
                'date_naissance' => '2001-12-05',
                'lieu_naissance' => 'Casablanca',
                'telephone' => '+212 6 11 22 33 10',
                'adresse' => '78 Rue Abdelmoumen, Casablanca',
                'status' => 'diplome',
            ],
            [
                'nom' => 'Bensalem',
                'prenom' => 'Mehdi',
                'apogee' => '78901234',
                'cin' => 'UV789012',
                'email' => 'mehdi.bensalem@ensa.ac.ma',
                'date_naissance' => '2003-08-27',
                'lieu_naissance' => 'Salé',
                'telephone' => '+212 6 11 22 33 11',
                'adresse' => '9 Rue Moulay Ismail, Salé',
                'status' => 'actif',
            ],
            [
                'nom' => 'El Fihri',
                'prenom' => 'Khadija',
                'apogee' => '89012345',
                'cin' => 'WX890123',
                'email' => 'khadija.elfihri@ensa.ac.ma',
                'date_naissance' => '2004-10-03',
                'lieu_naissance' => 'Tétouan',
                'telephone' => '+212 6 11 22 33 12',
                'adresse' => '31 Avenue Youssef Ben Tachfine, Tétouan',
                'status' => 'actif',
            ],
            [
                'nom' => 'Rafik',
                'prenom' => 'Hassan',
                'apogee' => '90123456',
                'cin' => 'YZ901234',
                'email' => 'hassan.rafik@ensa.ac.ma',
                'date_naissance' => '2003-03-16',
                'lieu_naissance' => 'Kénitra',
                'telephone' => '+212 6 11 22 33 13',
                'adresse' => '44 Boulevard Mohammed Diouri, Kénitra',
                'status' => 'actif',
            ],
            [
                'nom' => 'Moussaoui',
                'prenom' => 'Imane',
                'apogee' => '01234567',
                'cin' => 'ZA012345',
                'email' => 'imane.moussaoui@ensa.ac.ma',
                'date_naissance' => '2004-05-21',
                'lieu_naissance' => 'El Jadida',
                'telephone' => '+212 6 11 22 33 14',
                'adresse' => '19 Rue de la Plage, El Jadida',
                'status' => 'actif',
            ],
            [
                'nom' => 'Boudhrioua',
                'prenom' => 'Younes',
                'apogee' => '13579246',
                'cin' => 'BC135792',
                'email' => 'younes.boudhrioua@ensa.ac.ma',
                'date_naissance' => '2001-07-09',
                'lieu_naissance' => 'Rabat',
                'telephone' => '+212 6 11 22 33 15',
                'adresse' => '67 Avenue Hassan II, Rabat',
                'status' => 'diplome',
            ],
            // Additional students for variety
            [
                'nom' => 'Zahraoui',
                'prenom' => 'Salma',
                'apogee' => '24681357',
                'cin' => 'DE246813',
                'email' => 'salma.zahraoui@ensa.ac.ma',
                'date_naissance' => '2003-12-11',
                'lieu_naissance' => 'Casablanca',
                'telephone' => '+212 6 11 22 33 16',
                'adresse' => '88 Rue Zerktouni, Casablanca',
                'status' => 'actif',
            ],
            [
                'nom' => 'Hamdaoui',
                'prenom' => 'Rachid',
                'apogee' => '36925814',
                'cin' => 'FG369258',
                'email' => 'rachid.hamdaoui@ensa.ac.ma',
                'date_naissance' => '2004-02-28',
                'lieu_naissance' => 'Fès',
                'telephone' => '+212 6 11 22 33 17',
                'adresse' => '52 Derb El Miter, Fès',
                'status' => 'actif',
            ],
            [
                'nom' => 'Ouali',
                'prenom' => 'Zineb',
                'apogee' => '14725836',
                'cin' => 'HI147258',
                'email' => 'zineb.ouali@ensa.ac.ma',
                'date_naissance' => '2003-04-07',
                'lieu_naissance' => 'Marrakech',
                'telephone' => '+212 6 11 22 33 18',
                'adresse' => '21 Avenue Yacoub El Mansour, Marrakech',
                'status' => 'actif',
            ],
            [
                'nom' => 'Semlali',
                'prenom' => 'Anas',
                'apogee' => '25836914',
                'cin' => 'JK258369',
                'email' => 'anas.semlali@ensa.ac.ma',
                'date_naissance' => '2004-09-14',
                'lieu_naissance' => 'Tanger',
                'telephone' => '+212 6 11 22 33 19',
                'adresse' => '37 Rue de Belgique, Tanger',
                'status' => 'actif',
            ],
            [
                'nom' => 'Lahlou',
                'prenom' => 'Hiba',
                'apogee' => '36914725',
                'cin' => 'LM369147',
                'email' => 'hiba.lahlou@ensa.ac.ma',
                'date_naissance' => '2003-01-20',
                'lieu_naissance' => 'Rabat',
                'telephone' => '+212 6 11 22 33 20',
                'adresse' => '63 Avenue Annakhil, Rabat',
                'status' => 'actif',
            ],
            [
            'nom' => 'Alamii',
            'prenom' => 'Mohammmed',
            'apogee' => '123456789',
            'cin' => 'AB1234567',
            'email' => 'oumhella.abdellatif@etu.uae.ac.ma',
            'date_naissance' => '2003-05-15',
            'lieu_naissance' => 'Casablanca',
            'telephone' => '+212 6 11 22 33 01',
            'adresse' => '25 Rue des Écoles, Casablanca',
            'status' => 'actif',
        ],
        ];

        foreach ($etudiants as $etudiant) {
            Etudiant::create($etudiant);
        }
    }
}
